config/routes.rb
Rails.application.routes.draw do
  resources :crimes do 
    collection { post :import }
  end
  

  root 'crimes#index'

end

app/models/crime.rb
class Crime < ActiveRecord::Base
  has_attached_file :file

  def self.import(file)
    CSV.foreach(file_path, :headers => true) do |row|
     Crime.create!(row.to_hash)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  before_action :set_crime, only: [:show, :edit, :update, :destroy]

  # GET /crimes
  # GET /crimes.json
  def index
    @crimes = Crime.all
  end

  # GET /crimes/1
  # GET /crimes/1.json
  def show
  end

  # GET /crimes/new
  def new
    @crime = Crime.new
  end

  # GET /crimes/1/edit
  def edit
  end

  # POST /crimes
  # POST /crimes.json
  def create
    @crime = Crime.new(crime_params)

    respond_to do |format|
      if @crime.save
        format.html { redirect_to @crime, notice: 'Crime was successfully created.' }
        format.json { render :show, status: :created, location: @crime }
      else
        format.html { render :new }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crimes/1
  # PATCH/PUT /crimes/1.json
  def update
    respond_to do |format|
      if @crime.update(crime_params)
        format.html { redirect_to @crime, notice: 'Crime was successfully updated.' }
        format.json { render :show, status: :ok, location: @crime }
      else
        format.html { render :edit }
        format.json { render json: @crime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crimes/1
  # DELETE /crimes/1.json
  def destroy
    @crime.destroy
    respond_to do |format|
      format.html { redirect_to crimes_url, notice: 'Crime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def import
    begin
      Product.import(params[:file])
      redirect_to root_url, notice: "Products imported."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crime
      @crime = Crime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crime_params
      params.require(:crime).permit(:description, :year, :month, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crimes_helper.rb
module CrimesHelper
end

app/views/crimes/_form.html.erb
<%= form_for(@crime) do |f| %>
  <% if @crime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crime.errors.count, "error") %> prohibited this crime from being saved:</h2>

      <ul>
      <% @crime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crimes/edit.html.erb
<h1>Editing Crime</h1>

<%= render 'form' %>

<%= link_to 'Show', @crime %> |
<%= link_to 'Back', crimes_path %>

app/views/crimes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Crimes</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Year</th>
      <th>Month</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crimes.each do |crime| %>
      <tr>
        <td><%= crime.description %></td>
        <td><%= crime.year %></td>
        <td><%= crime.month %></td>
        <td><%= crime.location %></td>
        <td><%= link_to 'Show', crime %></td>
        <td><%= link_to 'Edit', edit_crime_path(crime) %></td>
        <td><%= link_to 'Destroy', crime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Import Crimes</h2>

<%= form_tag import_crimes_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Load Crime Zones" %>
<% end %>

<br>

<%= link_to 'New Crime', new_crime_path %>

app/views/crimes/new.html.erb
<h1>New Crime</h1>

<%= render 'form' %>



<%= form_for(@crime, :html => {:multipart => true}) do |f| %>
<div class="field">
   <%= f.label :avatar %><br />
   <%= f.file_field :avatar %>
  </div>
<% end %>
<br>


<%= link_to 'Back', crimes_path %>

app/views/crimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @crime.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @crime.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @crime.month %>
</p>

<p>
  <strong>Location:</strong>
  <%= @crime.location %>
</p>

<%= link_to 'Edit', edit_crime_path(@crime) %> |
<%= link_to 'Back', crimes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WatchOutApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>